### ISSUE TITLE
Incorporar Nueva Sección de Tecnologia

### ISSUE THREAD

**Issue by juanpy01** [emanuelAlavar/portfolio-template#1]
Hola Emanuel, propongo incorporar una nueva sección a tu Portfolio.
La nueva sección se llamara Tecnologías, que serán las que utilizas para tus proyectos.

**Comment by emanuelAlavar** [comment]
Hola Juan, adelante con esa nueva sección!

**Comment by emanuelAlavar** [comment]
Issue cerrado
